spring.application.name=ecommerce
# 1. URL: jdbc:postgresql://HOST:PUERTO/NOMBRE_DB
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres

# 2. USUARIO: Es largo (postgres + punto + id del proyecto)
spring.datasource.username=postgres.txhbupcnumlrfcoscafk

# 3. CONTRASEÑA: La que pusiste al crear el proyecto (¡No te la olvides!)
spring.datasource.password=DHOvZFx9lrmDWZTn

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true